### ISSUE TITLE
Can't access epam git to download 

### ISSUE THREAD

**Issue by Developer-jin** [xen-troops/meta-xt-prod-devel#133]
ssh://git@gitpct.epam.com/epmd-aepr/ can't access,
run make return error:
ninja: error: 'img_ddk_um', needed by 'Pie_OUT/target/product/xenvm/obj/KERNEL_MODULES/pvrsrvkm.ko', missing and no known rule to make it

**Comment by aanisov** [comment]
Hello @Developer-jin,

Unfortunately, that part is proprietary, so you can not access it unless you have an NDA.

**Comment by Developer-jin** [comment]
Thank you very much,
can I build the xen aosp without these vender packets?

**Comment by arminn** [comment]
Hello @Developer-jin 

I suppose you can disable(comment out) all graphics dependencies in device.mk ( https://github.com/xen-troops/android_device_xenvm/blob/android-9.0.0_r3-xt0.2/device.mk#L200 )
and after that,  it should be possible to build all from the source.

**Comment by Developer-jin** [comment]
Thank you!
I will try it later!
