### ISSUE TITLE
Fix PVR KM udev rule for passthrough

### ISSUE THREAD

**Issue by andr2000** [xen-troops/meta-xt-prod-devel#14]
recipes-domu/domu-image-weston/files/meta-xt-prod-extra/recipes-graphics/gles-module/files/72-pvr-seat.rules.patch must be reworked as passthrough path folder does not exist anymore:

DEVPATH=="/devices/platform/fd000000.gsx/drm/*"

**Comment by iartemenko** [comment]
Fixed-in: 7f21f93757f2594de92ba21a3c904539ad864af5
