### ISSUE TITLE
Salvator-X M3 dts' needs to be checked wrt IPMMU usage

### ISSUE THREAD

**Issue by andr2000** [xen-troops/meta-xt-prod-devel#24]
Please check [dom0](https://github.com/xen-troops/meta-xt-prod-devel/blob/master/recipes-dom0/dom0-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas/r8a7796-salvator-x-dom0.dts)
and [domu](https://github.com/xen-troops/meta-xt-prod-devel/blob/master/recipes-dom0/dom0-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas/r8a7796-salvator-x-domu.dts) files wrt IPMMU settings.

**Comment by otyshchenko1** [comment]
On the whole IPMMU settings are correct. But, there will be additional changes #26

**Comment by otyshchenko1** [comment]
Merged

**Comment by otyshchenko1** [comment]
@andr2000 pls close issue you opened
