### ISSUE TITLE
The inc/xen-version.inc file has dependency on the other external layer which is not correct and should be resolved

### ISSUE THREAD

**Issue by otyshchenko1** [xen-troops/meta-xt-prod-devel#279]
Please see details at https://github.com/xen-troops/meta-xt-prod-devel/pull/275

**Comment by rshym** [comment]
Seems that this issue is fixed by moving of xen-version.inc to separate layer meta-xt-prod-domx by commit 
e30a32c20a2abf16657d4ba5b7becf7b1677dc0e "move shared inc files to separate recipe".

Can we close this issue?

**Comment by otyshchenko1** [comment]
Looks like, it's time to close
