### ISSUE TITLE
Long path to the android OUT_DIR will lead to building fail

### ISSUE THREAD

**Issue by arminn** [xen-troops/meta-xt-prod-devel#338]
Should be fixed by:

1. https://github.com/xen-troops/linux/pull/104
2. https://github.com/xen-troops/android_device_xenvm/pull/56
3. TODO: patch on prod-devel which will not set OUT_DIR

**Comment by rshym** [comment]
Patch that removes setting of OUT_DIR is part of https://github.com/xen-troops/meta-xt-images/pull/197
Testing is ongoing.

**Comment by rshym** [comment]
All required patches are merged:
xen-troops/linux#104
xen-troops/android_device_xenvm#56
xen-troops/meta-xt-images#197

Product was built with quite long base path - no issue was observed.
