### ISSUE TITLE
There should be a separate repository for "arm-trusted-firmware" development.

### ISSUE THREAD

**Issue by otyshchenko1** [xen-troops/meta-xt-prod-devel#35]
You can find it at "path-to-yocto/meta-renesas/meta-rcar-gen3/recipes-bsp/arm-trusted-firmware/" location.
SCR_URI should be modified to use ARM-TF from xen-troops instead of renesas-rcar github.

**Comment by iartemenko** [comment]
Fixed in: b921b38c3d5fba7d0159ab6b5d3448cb4d425b1c #35
