### ISSUE TITLE
[HIGH]python-clang_5.0.post2.bb - move in the separate layer (building proprietary graphics)

### ISSUE THREAD

**Issue by iusyk** [xen-troops/meta-xt-prod-devel#350]
BTW, we already have a separate layer for building proprietary graphics packages. I believe that python-clang_5.0.post2.bb recipe should live there. In this case, we don't need this fix at all.
steps
move recipe python-clang_5.0.post2.bb
reveet commit based at https://github.com/xen-troops/meta-xt-prod-devel/pull/347

**Comment by rshym** [comment]
May be I'm wrong, but I suspect that issue is fixed after merge of https://github.com/xen-troops/meta-xt-images/pull/211 and may be closed.

**Comment by iusyk** [comment]
fixed xen-troops/meta-xt-images#211
